import Intro from "./components/intro/Intro";

export default function Home() {
  return (
    <>
     <Intro />
     <h1>Hello</h1>
     <h1>Hello</h1>
     <h1>Hello</h1>
     <h1>Hello</h1>
     <h1>Hello</h1>
     <h1>Hello</h1>
     <h1>Hello</h1>
     <h1>Hello</h1>
     <h1>Hello</h1>
     <h1>Hello</h1>
     <h1>Hello</h1>
     <h1>Hello</h1>
     <h1>Hello</h1>
     <h1>Hello</h1>
     <h1>Hello</h1>
     <h1>Hello</h1>
     <h1>Hello</h1>
     <h1>Hello</h1>
     <h1>Hello</h1>
     <h1>Hello</h1>
     <h1>Hello</h1>
     <h1>Hello</h1>
     <h1>Hello</h1>
     <h1>Hello</h1>
     <h1>Hello</h1>
     <h1>Hello</h1>
     <h1>Hello</h1>
     <h1>Hello</h1>
     <h1>Hello</h1>
     <h1>Hello</h1>
     <h1>Hello</h1>
     <h1>Hello</h1>
     <h1>Hello</h1>
     <h1>Hello</h1>
     <h1>Hello</h1>
     <h1>Hello</h1>
     <h1>Hello</h1>
     <h1>Hello</h1>
     <h1>Hello</h1>
     <h1>Hello</h1>
     <h1>Hello</h1>
     <h1>Hello</h1>
     <h1>Hello</h1>
     <h1>Hello</h1>
     <h1>Hello</h1>
     <h1>Hello</h1>
     <h1>Hello</h1>
     <h1>Hello</h1>
     <h1>Hello</h1>
     <h1>Hello</h1>
     <h1>Hello</h1>
     <h1>Hello</h1>
     <h1>Hello</h1>
     <h1>Hello</h1>
     <h1>Hello</h1>
     <h1>Hello</h1>
     <h1>Hello</h1>
     <h1>Hello</h1>
     <h1>Hello</h1>
     <h1>Hello</h1>
    </>
  );
}
